full_name = input("Ваші прізвище, ім'я, по-батькові? ")
age = input("Скільки Вам років? ")
place_living = input("Де Ви живете? ")
place_study = input("Де Ви навчаєтесь? ")
group_num = input("Номер Вашої групи: ")
number_in_group = input("Який Ваш порядковий номер у списку групи? ")

# Питання з таблиці
how_doing = input("Як справи? ")
how_feeling = input("Як Ви себе почуваєте? ")
when_home = input("Коли будете вдома? ")
zno_ukr_mark = input("Яку оцінку отримав на ЗНО по українській мові? ")
today_sunny = input("Сьогодні сонячно? ")
when_quarantine = input("Коли нарешті карантин? ")
friend_name = input("Як звати Вашого друга? ")
if_go_magistrate = input("Ви думаєте вступати у магістратуру? ")
textbook_color = input("Якого кольору Ваш зошит? ")
mood_today = input("Який Ваш настрій сьогодні? ")

print("---ПІДСУМОК---")
print(f"Ваше ім'я - {full_name}")
print(f"Ваш вік - {age}")
print(f"Ви живете в {place_living}")
print(f"Ви навчаєтесь в {place_study}")
print(f"Номер Вашої групи - {group_num}")
print(f"Порядковий номер в списку групи - {number_in_group}")